wow:
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
	go run main.go
